apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mongo 
spec: 
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
              protocol: TCP
              name: mongo-port
---
apiVersion: v1 
kind: Service 
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo-port
  type: LoadBalancer
  selector:
    app: mongo
    