apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: restapi
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate 
  selector:
    matchLabels:
      app: restapi
  replicas: 1
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - image: sparrow46world/restapi
          name: restapi
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
              protocol: TCP
              name: api-port
          env:
            - name: "MongoHost"
              value: "mongo"
            - name: "JaegerHost"
              value: "jaeger-udp"
            - name: "ZipkinHost"
              value: "zipkin"
            - name: "ELKHost"
              value: "elasticsearch"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: restapi 
spec: 
  ports: 
    - port: 4000
      targetPort: 80
      protocol: TCP 
      name: api-port
  type: LoadBalancer 
  selector:
    app: restapi 